### ISSUE TITLE
Error when dowloading in python 3.11.5 

### ISSUE THREAD

**Issue by shhossain** [divijbindlish/parse-torrent-name#36]
Error Info:
```bash
(base) PS C:\sifat\code\python> pip install parse-torrent-name
Collecting parse-torrent-name
  Using cached parse-torrent-name-1.1.1.tar.gz (9.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\sifat\AppData\Local\Temp\pip-install-9g3f47oe\parse-torrent-name_a64ae7154b3549c0a56ea6b23b3427f0\setup.py", line 5, in <module>
          description = f.read()
                        ^^^^^^^^
        File "C:\Users\sifat\miniconda3\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 292: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by dmachard** [comment]
If you are looking for an alternative parser.
I developed a lightweight library called [releascenify](https://github.com/dmachard/python-releasify) (also available on [PyPI](https://pypi.org/project/releascenify/)).
